name: PR Test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.6]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install pynetbox and testing packages.
        run: pip install . pycodestyle

      - name: Run Linter
        run: |
          pycodestyle pynetbox
          pycodestyle --ignore=E501 tests
          
      - name: Run Tests
        run: python -m unittest discover

